### ISSUE TITLE
posting git commit messages

### ISSUE THREAD

**Issue by andy5995** [RJ/irccat#20]
Could this be used for posting git commit messages, as well as svn?

**Comment by jwheare** [comment]
Yes, it just listens on a TCP port for any text. So as long as you have something that sends the commit message as text this'll work for you. It doesn't handle anything to do with git directly though.

Cheers.

**Comment by andy5995** [comment]
Ok, thanks, @jwheare. Specifically, I was looking for an IRC bot that I could run on a server at home, and post to a channel automatically - when new commits are made, and Github issues (tickets) are created and updated. I've seen this on dev channels before and really have no idea how to set something like that up. I've set up an IRC bot before, but not one that does what I'm looking for.

**Comment by jwheare** [comment]
Take a look at notifico: https://n.tkte.ch/

**Comment by andy5995** [comment]
Thanks!
